### ISSUE TITLE
memory allocation failed

### ISSUE THREAD

**Issue by cx4** [1zlab/1ZLAB-Source-Code#1] opened 2018-12-20 11:05 UTC
When I use ESP8266 appeared error

> >>> import upip
> >>> upip.install('emp-1zlab')
> Installing to: /lib/
> Error installing 'emp-1zlab': memory allocation failed, allocating %u bytes, packages may be partially installed

**Comment by Singein** [comment] 2018-12-20 12:04
Sorry about this,  even though you got the wrong place to report this issue.
We have already known this issue on ESP8266. This error always caused by the lack of memory on ESP8266 platform. 
Fortunately, there is a compatible solution here that will be released in the next few days, please stay tuned

please move your attention to the repo below:
<https://github.com/Easy-MicroPython/EMP-FOR-ESP8266>

**Comment by Singein** [comment] 2018-12-21 13:18
Solution：
https://github.com/Easy-MicroPython/EMP-FOR-ESP8266

**Closed as completed by Singein** 2018-12-21 13:18 UTC
